version: '3.8'

# Здесь мы описываем все сервисы (контейнеры), из которых состоит наша система.
services:
  # Даем нашему сервису логическое имя. Назовем его 'postgres'.
  postgres:
    # Указываем, какой образ использовать. Мы берем официальный образ PostgreSQL
    image: postgres:15-alpine

    # Имя контейнера,
    container_name: tennis_postgres

    # Здесь мы настраиваем сам PostgreSQL внутри контейнера.
    # Мы передаем переменные окружения, которые прочитает скрипт запуска PostgreSQL.
    environment:
      POSTGRES_DB: tennis_db          # Имя базы данных, которую нужно создать при первом запуске.
      POSTGRES_USER: tennis_user      # Имя пользователя.
      POSTGRES_PASSWORD: test  # Пароль для этого пользователя.

    # Пробрасываем порты. Это самая важная часть для подключения.
    # Формат "ПОРТ_НА_ВАШЕЙ_МАШИНЕ:ПОРТ_ВНУТРИ_КОНТЕЙНЕРА"
    # "5432:5432" означает, что порт 5432 на вашем компьютере (localhost)
    # будет напрямую соединен с портом 5432 внутри контейнера, где работает PostgreSQL.
    ports:
      - "54793:5432"

    # Сохраняем данные. Без этого блока все данные в БД будут удалены
    # при остановке и удалении контейнера. Этот блок создает "том" (volume)
    # и монтирует его в папку, где PostgreSQL хранит свои данные.
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Пробрасываем папку со скриптами в специальную папку внутри контейнера докера
      - ./db-init:/docker-entrypoint-initdb.d
# Объявляем том, который мы использовали выше. Docker сам будет им управлять.
volumes:
  postgres_data: